### ISSUE TITLE
ODM2NjU1MTEyMDIxMjEzMjI0.YIhJyw.OqyrfFdxyKGEz-vs3r8tMUUXlsY

### ISSUE THREAD

**Issue by mangoess** [Supelion/Bloop#1]
ODM2NjU1MTEyMDIxMjEzMjI0.YIhJyw.OqyrfFdxyKGEz-vs3r8tMUUXlsY

your welcome!

**Comment by mangoess** [comment]
msg me on discord for more info

**Comment by mtbtrq** [comment]
uh wut

**Comment by mangoess** [comment]
What does that string remind you of?

**Comment by mtbtrq** [comment]
a bot token?

**Comment by mangoess** [comment]
Which bot specifically?

**Comment by mtbtrq** [comment]
my bot?
also check dc

**Comment by mangoess** [comment]
Can't it's blocked rn, give me a couple hours.
Also, I'd highly advise you to "check" the 🎫 
hope u have a great day

**Comment by mtbtrq** [comment]
I always regenerate my bot tokens everytime I post a update, even though I thoroughly check it (is what I said on discord)
and thanks, u2
also I like mangoes too now
